export const DEFAULT_MATCH_DURATION_MINUTES = 90;
export const MATCH_DURATION_OPTIONS_MINUTES = [45, 60, 90, 120] as const;
export const MIN_MATCH_DURATION_MINUTES = 30;
export const MAX_MATCH_DURATION_MINUTES = 240;
