spring.application.name=footy-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/footy
spring.datasource.username=footy
spring.datasource.password=footy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true